name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.PGUSER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Restore dependencies
        run: npm ci
      - name: Apply migrations
        run: npm run migrate:test
        env:
          PGHOST_TEST: localhost
          PGPORT_TEST: 5432
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          DATABASE_URL: postgresql://${{ secrets.PGUSER_TEST }}:${{ secrets.PGPASSWORD_TEST }}@localhost:5432/${{ secrets.PGDATABASE_TEST }}
      - name: Run tests
        run: npm test
        env:
          PGHOST_TEST: localhost
          PGPORT_TEST: 5432
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          ACCESS_TOKEN_KEY: supersecretaccesstoken
          REFRESH_TOKEN_KEY: supersecretrefreshtoken
          ACCCESS_TOKEN_AGE: 1h # Perbaiki typo ACCCESS_TOKEN_AGE menjadi ACCESS_TOKEN_AGE jika ada
