# .github/workflows/ci.yml
name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }} # Gunakan secret
          POSTGRES_USER: ${{ secrets.PGUSER_TEST }} # Gunakan secret
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }} # Gunakan secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: node-pg-migrate up
        env:
          # Variabel lingkungan standar yang akan dibaca oleh node-pg-migrate
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: ${{ secrets.PGUSER_TEST }} # Gunakan secret
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }} # Gunakan secret
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }} # Gunakan secret

      - name: Run tests (Unit, Integration, Functional)
        run: npm test
        env:
          # Variabel lingkungan dengan sufiks _TEST yang dibaca oleh pool.js aplikasi Anda
          PGHOST_TEST: localhost
          PGPORT_TEST: 5432
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }} # Gunakan secret
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }} # Gunakan secret
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }} # Gunakan secret
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
